dtb-$(CONFIG_ARCH_FSL_LS2085A) += fsl-ls2085a-simu.dtb
dtb-$(CONFIG_ARCH_FSL_IMX8DV) += fsl-imx8dv-zebu.dtb
dtb-$(CONFIG_ARCH_FSL_IMX8DV) += fsl-imx8dv-sabreauto.dtb
dtb-$(CONFIG_ARCH_FSL_IMX8DV) += fsl-imx8dv-zebu_ca72.dtb fsl-imx8dv-zebu_gpu.dtb
dtb-$(CONFIG_ARCH_FSL_IMX8DV) += fsl-imx8dv-zebu_ca72.dtb fsl-imx8dv-zebu_vpu.dtb
dtb-$(CONFIG_ARCH_FSL_IMX8DV) += fsl-imx8dv-sabreauto_gpu.dtb

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
