dtb-$(CONFIG_ARCH_LAYERSCAPE) += fsl-ls1043a-qds.dtb
dtb-$(CONFIG_ARCH_LAYERSCAPE) += fsl-ls1043a-rdb.dtb
dtb-$(CONFIG_ARCH_LAYERSCAPE) += fsl-ls2080a-qds.dtb
dtb-$(CONFIG_ARCH_LAYERSCAPE) += fsl-ls2080a-rdb.dtb
dtb-$(CONFIG_ARCH_LAYERSCAPE) += fsl-ls2080a-simu.dtb
dtb-$(CONFIG_ARCH_FSL_IMX8QM) += fsl-imx8qm-lpddr4-arm2.dtb fsl-imx8qm-lpddr4-arm2-m4.dtb fsl-imx8qm-lpddr4-arm2_ca53.dtb fsl-imx8qm-lpddr4-arm2_ca72.dtb fsl-imx8qm-zebu.dtb fsl-imx8qm-zebu_ca53.dtb fsl-imx8qm-zebu_ca72.dtb fsl-imx8qm-zebu_gpu.dtb fsl-imx8qm-zebu_audio.dtb
dtb-$(CONFIG_ARCH_FSL_IMX8QXP) += fsl-imx8qxp-lpddr4-arm2.dtb fsl-imx8qxp-lpddr4-arm2-m4.dtb fsl-imx8qxp-zebu.dtb fsl-imx8qxp-zebu_gpu.dtb fsl-imx8qxp-zebu_audio.dtb

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
