/* ========================================================================== */
/*  Project  : cafe                                                           */
/*  Module   : zv_xreg_defines                                                */
/*  File     : zv_xreg_defines.h                                              */
/*                                                                            */
/*  Author   : reggen 1.56                                                    */
/*  Created  :                                                                */
/* -------------------------------------------------------------------------- */
/*  Comments :      !! AUTO-GENERATED-FILE - DO NOT EDIT !!                   */
/*                                                                            */
/*  COPYRIGHT:     Zenverge Inc. Proprietary and Confidential                 */
/*                      Copyright (c) 2015, Zenverge Inc.                     */
/*                            All rights reserved.                            */
/*                                                                            */
/*         Permission to use, modify or copy this code is prohibited          */
/*           without the express written consent of Zenverge Inc.             */
/*                                                                            */
/* ========================================================================== */

#ifndef __ZV_XREG_DEFINES_H__
#define __ZV_XREG_DEFINES_H__

#include "med_xreg_arb.h"
#include "med_scb.h"
#include "med_ppm.h"
#include "med_ppm_glbl_regs.h"
#include "med_ppm_sched_regs.h"
#include "med_ppm_pid_regs.h"
#include "med_ppm_scd_regs.h"
#include "med_misc_ctrl.h"
#include "med_misc_ctrl_reg.h"
#include "med_misc_ctrl_semaphore.h"
#include "med_timer_xreg_top.h"
#include "med_timer_op_regs.h"
#include "med_int_ctrl.h"
#include "med_int_ctrl_lcl_reg.h"
#include "med_int_ctrl_isr_bank.h"
#include "med_int_ctrl_iol_bank.h"
#include "med_xmem_register_if.h"
#include "med_xmem_secure_register_if.h"
#include "med_ddr_obfus_sbox_addr.h"
#include "med_fdma_reg.h"
#include "med_chan_reg.h"
#include "med_dma_core_chan_reg.h"
#include "med_mdma_reg.h"
#include "med_list.h"
#include "med_mdma_list_reg.h"
#include "med_mdma_hw_ls.h"
#include "med_mdma_hw_ls_reg.h"
#include "med_descr_int.h"
#include "med_descr_int_reg.h"
#include "med_chan.h"
#include "med_crypto.h"
#include "med_crypto_glbl_regs.h"
#include "med_crypto_chn_regs.h"
#include "med_crypto_aes_regs.h"
#include "med_crypto_multi2_regs.h"
#include "med_crypto_mem_access.h"
#include "med_global_reg_ctrl_xreg.h"
#include "med_global_reg.h"
#include "med_scb_blk_ctrl.h"
#include "med_dec_cache.h"
#include "med_mc_cache_reg.h"
#include "med_dec_cache_blk_ctrl.h"
#include "med_clkrst.h"
#include "med_clkrst_pll_reg.h"
#include "med_clkrst_pin_mux.h"
#include "med_clkrst_clk_and_rst.h"
#include "med_clkrst_boot.h"
#include "med_clkrst_int.h"
#include "med_clkrst_scratch.h"
#include "med_clkrst_rng.h"
#include "med_dec_mfd.h"
#include "med_mfd_blk_ctrl.h"
#include "med_dec_hevc.h"
#include "med_crb.h"
#include "med_crb_xreg_regs.h"
#include "med_hevc_dec_iq_it.h"
#include "med_mvb_reg.h"
#include "med_fifo_access.h"
#include "med_hevc_wp_regfile.h"
#include "med_dec_concat_xreg.h"
#include "med_ed_get_bits.h"
#include "med_hevc_cabac_dec_regs.h"
#include "med_concat_fifo_regs.h"
#include "med_ed_if_regs.h"
#include "med_global_reg_dec.h"
#include "med_dec_hevc_blk_ctrl.h"
#include "med_fwpu.h"
#include "med_spu_cpu_regs.h"
#include "med_vbib.h"
#include "med_scaler_top.h"
#include "med_hscl_reg.h"
#include "med_vscl_reg.h"
#include "med_scl_mvrp.h"
#include "med_me_mvrp_gpr.h"
#include "med_me_mvrp_psr.h"
#include "med_me_mvrp_dbg.h"
#include "med_me_mvrp_brt.h"
#include "med_scaler_buffer_regs.h"
#include "med_scaler_vid_buffer.h"
#include "med_scaler_vid_buffer_part.h"
#include "med_scaler_vid_buffer_config.h"
#include "med_scaler_buffer_regs_ddr_dom.h"
#include "med_yuv_packer.h"
#include "med_osd_regs.h"
#include "med_deint_regs.h"
#include "med_css_regs.h"
#include "med_vbib_glue_regs.h"
#include "med_vbib_blk_ctrl.h"
#include "med_xuvi.h"
#include "med_xuvi_glbl_regs.h"
#include "med_xuvi_stc_regs.h"
#include "med_xuvi_io_regs.h"
#include "med_xuvi_cbar_regs.h"
#include "med_xuvi_ts_regs.h"
#include "med_xuvi_aud_regs.h"
#include "med_xuvi_vid_regs.h"
#include "med_xuvi_pid_regs.h"
#include "med_xuvi_xdma_regs.h"
#include "med_xuvi_blk_ctrl.h"
#include "med_me_top.h"
#include "med_me.h"
#include "med_me_srcmb_param.h"
#include "med_me_regfile.h"
#include "med_me_intrpts.h"
#include "med_me_dma.h"
#include "med_fp_results.h"
#include "med_sp_results.h"
#include "med_fill_results.h"
#include "med_fp_reg.h"
#include "med_fp_sad.h"
#include "med_me_refidx.h"
#include "med_mvr_results.h"
#include "med_me_col_xreg.h"
#include "med_enc_in.h"
#include "med_mepu_cpu_regs.h"
#include "med_me_buffer.h"
#include "med_me_buffer_luma.h"
#include "med_me_vid_buffer.h"
#include "med_me_vid_buffer_int.h"
#include "med_me_buffer_chroma.h"
#include "med_me_top_blk_ctrl.h"
#include "med_venc.h"
#include "med_mctf.h"
#include "med_emvp_xreg.h"
#include "med_emvp_debug_fb_ps.h"
#include "med_emvp_debug_core.h"
#include "med_quant_xreg.h"
#include "med_ee_xreg_brg.h"
#include "med_ee_if.h"
#include "med_h264_cavlc_enc.h"
#include "med_vlc.h"
#include "med_ee_put_bits.h"
#include "med_ee_xreg_regfile.h"
#include "med_deblock_xreg.h"
#include "med_deblock_debug_core.h"
#include "med_deblock_debug_mv.h"
#include "med_deblock_debug_xreg_slice.h"
#include "med_deblock_debug_mem_ctrl.h"
#include "med_deblock_debug_output.h"
#include "med_deblock_debug_dei.h"
#include "med_ref_dmw.h"
#include "med_venc_blk_ctrl.h"
#include "med_venc_intra.h"
#include "med_sobel_reg.h"
#include "med_intra_dec_reg_hier.h"
#include "med_intra_dec_reg.h"
#include "med_fp_q_iq_top.h"
#include "med_venc_intra_blk_ctrl.h"
#include "med_spu.h"
#include "med_security_reg.h"
#include "med_otp_reg_if.h"
#include "med_rsa_ecc.h"
#include "med_spu_blk_ctrl.h"
#include "med_apb_mod.h"
#include "med_apb_regs.h"
#include "med_gpio_top.h"
#include "med_apb_mod_blk_ctrl.h"
#include "med_pcie.h"
#include "med_pcie_blk_ctrl.h"

#endif
