/*==========================================================================*/
/*!
 * @file svc/wdog/rpc.h
 *
 * Header file for the WDOG RPC implementation.
 *
 * @addtogroup WDOG_SVC
 * @{
 */
/*==========================================================================*/

/* DO NOT EDIT - This file auto generated by rpc_h.pl */

#ifndef _SC_WDOG_RPC_H
#define _SC_WDOG_RPC_H

/* Includes */

#include <soc/imx8/sc/rpc.h>

/* Defines */

/* Types */

typedef enum wdog_func_e
{
    WDOG_FUNC_UNKNOWN,
    WDOG_FUNC_SET_TIMEOUT,
    WDOG_FUNC_START,
    WDOG_FUNC_STOP,
    WDOG_FUNC_PING,
    WDOG_FUNC_GET_STATUS
} wdog_func_t;

/* Functions */

void wdog_dispatch(sc_rm_pt_t caller_pt, sc_rpc_msg_t *msg);

#endif /* _SC_WDOG_RPC_H */

/**@}*/

