/*==========================================================================*/
/*!
 * @file svc/otp/rpc.h
 *
 * Header file for the OTP RPC implementation.
 *
 * @addtogroup OTP_SVC
 * @{
 */
/*==========================================================================*/

/* DO NOT EDIT - This file auto generated by rpc_h.pl */

#ifndef _SC_OTP_RPC_H
#define _SC_OTP_RPC_H

/* Includes */

/* Defines */

/* Types */

/*!
 * This type is used to indicate RPC OTP function calls.
 */
typedef enum otp_func_e
{
    OTP_FUNC_UNKNOWN, //!< Unknown function
    OTP_FUNC_READ, //!< Index for otp_read() RPC call
    OTP_FUNC_WRITE, //!< Index for otp_write() RPC call
    OTP_FUNC_SET_PERMISSIONS, //!< Index for otp_set_permissions() RPC call
} otp_func_t;

/* Functions */

/*!
 * @name Internal RPC Function
 * @{
 */

/*!
 * This function dispatches an incoming OTP RPC request.
 *
 * @param[in]     caller_pt   caller partition
 * @param[in]     msg         pointer to RPC message
 */
void otp_dispatch(sc_rm_pt_t caller_pt, sc_rpc_msg_t *msg);

/* @} */

#endif /* _SC_OTP_RPC_H */

/**@}*/

