obj-$(CONFIG_HAVE_IMX_MU) += mu/
obj-$(CONFIG_ARCH_FSL_IMX8QM) += sc/
obj-$(CONFIG_ARCH_FSL_IMX8QM) += pm-domains.o
obj-$(CONFIG_ARCH_FSL_IMX8MQ) += gpc-psci.o
obj-$(CONFIG_HAVE_IMX8_SOC) += soc-imx8.o
obj-$(CONFIG_XEN_IMX_SCMUBACK) += xen-scmuback.o
obj-$(CONFIG_XEN_IMX_SCMUFRONT) += xen-scmufront.o
