/*
** automatically generated make config, DO NOT edit
*/
#undef CONFIG_ZV_CHIP_CHISEL
#undef CONFIG_ZV_CHIP_CAFE
#define CONFIG_ZV_CHIP_MX8 1
#undef CONFIG_ZV_PCIE_EVK
#undef CONFIG_ZV_USB_EVK
#define CONFIG_ZV_HPU_EVK 1
#undef CONFIG_ZV_VAR_NONE
#define CONFIG_ZV_VAR_DV 1
#undef CONFIG_ZV_VAR_QMAX
#undef CONFIG_ZV_VAR_MSCALE
#undef CONFIG_HOST_PLATFORM_X86_LINUX
#undef CONFIG_HOST_PLATFORM_MIPS
#undef CONFIG_HOST_PLATFORM_ARM
#define CONFIG_HOST_PLATFORM_ARM64 1
#undef CONFIG_ZV4L2_USE_STUB_HPU_BUS
#define CONFIG_BUILD_TESTAPPS 1
#undef CONFIG_ENABLE_TESTAPPS_SDL
#define CONFIG_ZV4L2_USE_VB2 1
#undef CONFIG_ZV4L2_USE_FWSIM
