/*==========================================================================*/
/*!
 * @file svc/otp/rpc.h
 *
 * Header file for the OTP RPC implementation.
 *
 * @addtogroup OTP_SVC
 * @{
 */
/*==========================================================================*/

/* DO NOT EDIT - This file auto generated by rpc_h.pl */

#ifndef _SC_OTP_RPC_H
#define _SC_OTP_RPC_H

/* Includes */

#include <soc/imx8/sc/rpc.h>

/* Defines */

/* Types */

typedef enum otp_func_e
{
    OTP_FUNC_UNKNOWN,
    OTP_FUNC_READ,
    OTP_FUNC_WRITE,
    OTP_FUNC_SET_PERMISSIONS
} otp_func_t;

/* Functions */

void otp_dispatch(sc_rm_pt_t caller_pt, sc_rpc_msg_t *msg);

#endif /* _SC_OTP_RPC_H */

/**@}*/

