/*==========================================================================*/
/*!
 * @file svc/wdog/rpc.h
 *
 * Header file for the WDOG RPC implementation.
 *
 * @addtogroup WDOG_SVC
 * @{
 */
/*==========================================================================*/

/* DO NOT EDIT - This file auto generated by rpc_h.pl */

#ifndef _SC_WDOG_RPC_H
#define _SC_WDOG_RPC_H

/* Includes */

/* Defines */

/* Types */

/*!
 * This type is used to indicate RPC WDOG function calls.
 */
typedef enum wdog_func_e
{
    WDOG_FUNC_UNKNOWN, //!< Unknown function
    WDOG_FUNC_SET_TIMEOUT, //!< Index for wdog_set_timeout() RPC call
    WDOG_FUNC_START, //!< Index for wdog_start() RPC call
    WDOG_FUNC_STOP, //!< Index for wdog_stop() RPC call
    WDOG_FUNC_PING, //!< Index for wdog_ping() RPC call
    WDOG_FUNC_GET_STATUS, //!< Index for wdog_get_status() RPC call
} wdog_func_t;

/* Functions */

/*!
 * This function dispatches an incoming WDOG RPC request.
 *
 * @param[in]     caller_pt   caller partition
 * @param[in]     msg         pointer to RPC message
 */
void wdog_dispatch(sc_rm_pt_t caller_pt, sc_rpc_msg_t *msg);

#endif /* _SC_WDOG_RPC_H */

/**@}*/

