/*==========================================================================*/
/*!
 * @file svc/wdog/rpc_clnt.c
 *
 * File containing client-side RPC functions for the WDOG service. These
 * function are ported to clients that communicate to the SC.
 *
 * @addtogroup WDOG_SVC
 * @{
 */
/*==========================================================================*/

/* DO NOT EDIT - This file auto generated by rpc_clnt_c.pl */

/* Includes */

#include <soc/imx8/sc/types.h>
#include <soc/imx8/sc/svc/rm/api.h>
#include <soc/imx8/sc/svc/wdog/api.h>
#include "../../main/rpc.h"
#include "rpc.h"

/* Local Defines */

/* Local Types */

/* IDL: E8 SET_TIMEOUT(I32 timeout) */
sc_err_t sc_wdog_set_timeout(sc_ipc_t ipc, sc_wdog_time_t timeout)
{
    sc_rpc_msg_t msg;
    uint8_t result;

    RPC_VER(&msg) = SC_RPC_VERSION;
    RPC_SVC(&msg) = SC_RPC_SVC_WDOG;
    RPC_FUNC(&msg) = WDOG_FUNC_SET_TIMEOUT;
    RPC_D32(&msg, 0) = timeout;
    RPC_SIZE(&msg) = 2;

    sc_call_rpc(ipc, &msg, false);

    result = RPC_R8(&msg);
    return result;
}

/* IDL: E8 START(I1 lock) */
sc_err_t sc_wdog_start(sc_ipc_t ipc, bool lock)
{
    sc_rpc_msg_t msg;
    uint8_t result;

    RPC_VER(&msg) = SC_RPC_VERSION;
    RPC_SVC(&msg) = SC_RPC_SVC_WDOG;
    RPC_FUNC(&msg) = WDOG_FUNC_START;
    RPC_D8(&msg, 0) = lock;
    RPC_SIZE(&msg) = 2;

    sc_call_rpc(ipc, &msg, false);

    result = RPC_R8(&msg);
    return result;
}

/* IDL: E8 STOP() */
sc_err_t sc_wdog_stop(sc_ipc_t ipc)
{
    sc_rpc_msg_t msg;
    uint8_t result;

    RPC_VER(&msg) = SC_RPC_VERSION;
    RPC_SVC(&msg) = SC_RPC_SVC_WDOG;
    RPC_FUNC(&msg) = WDOG_FUNC_STOP;
    RPC_SIZE(&msg) = 1;

    sc_call_rpc(ipc, &msg, false);

    result = RPC_R8(&msg);
    return result;
}

/* IDL: E8 PING() */
sc_err_t sc_wdog_ping(sc_ipc_t ipc)
{
    sc_rpc_msg_t msg;
    uint8_t result;

    RPC_VER(&msg) = SC_RPC_VERSION;
    RPC_SVC(&msg) = SC_RPC_SVC_WDOG;
    RPC_FUNC(&msg) = WDOG_FUNC_PING;
    RPC_SIZE(&msg) = 1;

    sc_call_rpc(ipc, &msg, false);

    result = RPC_R8(&msg);
    return result;
}

/* IDL: E8 GET_STATUS(O32 timeout, O32 max_timeout, O32 remaining_time) */
sc_err_t sc_wdog_get_status(sc_ipc_t ipc, sc_wdog_time_t *timeout,
    sc_wdog_time_t *max_timeout, sc_wdog_time_t *remaining_time)
{
    sc_rpc_msg_t msg;
    uint8_t result;

    RPC_VER(&msg) = SC_RPC_VERSION;
    RPC_SVC(&msg) = SC_RPC_SVC_WDOG;
    RPC_FUNC(&msg) = WDOG_FUNC_GET_STATUS;
    RPC_SIZE(&msg) = 1;

    sc_call_rpc(ipc, &msg, false);

    if (timeout != NULL)
        *timeout = RPC_D32(&msg, 0);
    if (max_timeout != NULL)
        *max_timeout = RPC_D32(&msg, 4);
    if (remaining_time != NULL)
        *remaining_time = RPC_D32(&msg, 8);
    result = RPC_R8(&msg);
    return result;
}

/**@}*/

