/*==========================================================================*/
/*!
 * @file svc/misc/rpc.h
 *
 * Header file for the MISC RPC implementation.
 *
 * @addtogroup MISC_SVC
 * @{
 */
/*==========================================================================*/

/* DO NOT EDIT - This file auto generated by rpc_h.pl */

#ifndef _SC_MISC_RPC_H
#define _SC_MISC_RPC_H

/* Includes */

#include <soc/imx8/sc/rpc.h>

/* Defines */

/* Types */

typedef enum misc_func_e
{
    MISC_FUNC_UNKNOWN,
    MISC_FUNC_SET_CONTROL,
    MISC_FUNC_GET_CONTROL
} misc_func_t;

/* Functions */

void misc_dispatch(sc_rm_pt_t caller_pt, sc_rpc_msg_t *msg);

#endif /* _SC_MISC_RPC_H */

/**@}*/

