/*==========================================================================*/
/*!
 * @file svc/misc/rpc_clnt.c
 *
 * File containing client-side RPC functions for the MISC service. These
 * function are ported to clients that communicate to the SC.
 *
 * @addtogroup MISC_SVC
 * @{
 */
/*==========================================================================*/

/* DO NOT EDIT - This file auto generated by rpc_clnt_c.pl */

/* Includes */

#include <soc/imx8/sc/types.h>
#include <soc/imx8/sc/rpc.h>
#include <soc/imx8/sc/svc/rm/api.h>
#include <soc/imx8/sc/svc/misc/api.h>
#include "rpc.h"

/* Local Defines */

/* Local Types */

/* IDL: E8 SET_CONTROL(I16 resource, I32 ctrl, I32 val) */
sc_err_t sc_misc_set_control(sc_ipc_t ipc, sc_rsrc_t resource,
    sc_ctrl_t ctrl, uint32_t val)
{
    sc_rpc_msg_t msg;
    uint8_t result;

    RPC_VER(&msg) = SC_RPC_VERSION;
    RPC_SVC(&msg) = SC_RPC_SVC_MISC;
    RPC_FUNC(&msg) = MISC_FUNC_SET_CONTROL;
    RPC_D32(&msg, 0) = ctrl;
    RPC_D32(&msg, 4) = val;
    RPC_D16(&msg, 8) = resource;
    RPC_SIZE(&msg) = 4;

    sc_call_rpc(ipc, &msg, false);

    result = RPC_R8(&msg);
    return result;
}

/* IDL: E8 GET_CONTROL(I16 resource, I32 ctrl, O32 val) */
sc_err_t sc_misc_get_control(sc_ipc_t ipc, sc_rsrc_t resource,
    sc_ctrl_t ctrl, uint32_t *val)
{
    sc_rpc_msg_t msg;
    uint8_t result;

    RPC_VER(&msg) = SC_RPC_VERSION;
    RPC_SVC(&msg) = SC_RPC_SVC_MISC;
    RPC_FUNC(&msg) = MISC_FUNC_GET_CONTROL;
    RPC_D32(&msg, 0) = ctrl;
    RPC_D16(&msg, 4) = resource;
    RPC_SIZE(&msg) = 3;

    sc_call_rpc(ipc, &msg, false);

    if (val != NULL)
        *val = RPC_D32(&msg, 0);
    result = RPC_R8(&msg);
    return result;
}

/**@}*/

