/*==========================================================================*/
/*!
 * @file svc/rm/rpc_clnt.c
 *
 * File containing client-side RPC functions for the RM service. These
 * function are ported to clients that communicate to the SC.
 *
 * @addtogroup RM_SVC
 * @{
 */
/*==========================================================================*/

/* DO NOT EDIT - This file auto generated by rpc_clnt_c.pl */

/* Includes */

#include <soc/imx8/sc/types.h>
#include <soc/imx8/sc/svc/rm/api.h>
#include "../../main/rpc.h"
#include "rpc.h"

/* Local Defines */

/* Local Types */

/* IDL: E8 PARTITION_ALLOC(O8 pt, IB secure, IB isolated, IB restricted, IB confidential) */   
sc_err_t sc_rm_partition_alloc(sc_ipc_t ipc, sc_rm_pt_t *pt, bool secure,
    bool isolated, bool restricted, bool confidential)
{
    sc_rpc_msg_t msg;
    uint8_t result;

    RPC_VER(&msg) = SC_RPC_VERSION;
    RPC_SVC(&msg) = SC_RPC_SVC_RM;
    RPC_FUNC(&msg) = RM_FUNC_PARTITION_ALLOC;
    RPC_D8(&msg, 0) = secure;
    RPC_D8(&msg, 1) = isolated;
    RPC_D8(&msg, 2) = restricted;
    RPC_D8(&msg, 3) = confidential;
    RPC_SIZE(&msg) = 2;

    sc_call_rpc(ipc, &msg, false);

    result = RPC_R8(&msg);
    if (pt != NULL)
        *pt = RPC_D8(&msg, 0);
    return result;
}

/* IDL: E8 PARTITION_FREE(I8 pt) */   
sc_err_t sc_rm_partition_free(sc_ipc_t ipc, sc_rm_pt_t pt)
{
    sc_rpc_msg_t msg;
    uint8_t result;

    RPC_VER(&msg) = SC_RPC_VERSION;
    RPC_SVC(&msg) = SC_RPC_SVC_RM;
    RPC_FUNC(&msg) = RM_FUNC_PARTITION_FREE;
    RPC_D8(&msg, 0) = pt;
    RPC_SIZE(&msg) = 2;

    sc_call_rpc(ipc, &msg, false);

    result = RPC_R8(&msg);
    return result;
}

/* IDL: E8 PARTITION_STATIC(I8 pt, I4 did) */   
sc_err_t sc_rm_partition_static(sc_ipc_t ipc, sc_rm_pt_t pt,
    sc_rm_did_t did)
{
    sc_rpc_msg_t msg;
    uint8_t result;

    RPC_VER(&msg) = SC_RPC_VERSION;
    RPC_SVC(&msg) = SC_RPC_SVC_RM;
    RPC_FUNC(&msg) = RM_FUNC_PARTITION_STATIC;
    RPC_D8(&msg, 0) = pt;
    RPC_D8(&msg, 1) = did;
    RPC_SIZE(&msg) = 2;

    sc_call_rpc(ipc, &msg, false);

    result = RPC_R8(&msg);
    return result;
}

/* IDL: E8 PARTITION_LOCK(I8 pt) */   
sc_err_t sc_rm_partition_lock(sc_ipc_t ipc, sc_rm_pt_t pt)
{
    sc_rpc_msg_t msg;
    uint8_t result;

    RPC_VER(&msg) = SC_RPC_VERSION;
    RPC_SVC(&msg) = SC_RPC_SVC_RM;
    RPC_FUNC(&msg) = RM_FUNC_PARTITION_LOCK;
    RPC_D8(&msg, 0) = pt;
    RPC_SIZE(&msg) = 2;

    sc_call_rpc(ipc, &msg, false);

    result = RPC_R8(&msg);
    return result;
}

/* IDL: E8 GET_PARTITION(O8 pt) */
sc_err_t sc_rm_get_partition(sc_ipc_t ipc, sc_rm_pt_t *pt)
{
    sc_rpc_msg_t msg;
    uint8_t result;

    RPC_VER(&msg) = SC_RPC_VERSION;
    RPC_SVC(&msg) = SC_RPC_SVC_RM;
    RPC_FUNC(&msg) = RM_FUNC_GET_PARTITION;
    RPC_SIZE(&msg) = 1;

    sc_call_rpc(ipc, &msg, false);

    result = RPC_R8(&msg);
    if (pt != NULL)
        *pt = RPC_D8(&msg, 0);
    return result;
}

/* IDL: E8 SET_PARENT(I8 pt, I8 parent) */
sc_err_t sc_rm_set_parent(sc_ipc_t ipc, sc_rm_pt_t pt,
    sc_rm_pt_t parent)
{
    sc_rpc_msg_t msg;
    uint8_t result;

    RPC_VER(&msg) = SC_RPC_VERSION;
    RPC_SVC(&msg) = SC_RPC_SVC_RM;
    RPC_FUNC(&msg) = RM_FUNC_SET_PARENT;
    RPC_D8(&msg, 0) = pt;
    RPC_D8(&msg, 1) = parent;
    RPC_SIZE(&msg) = 2;

    sc_call_rpc(ipc, &msg, false);

    result = RPC_R8(&msg);
    return result;
}

/* IDL: E8 MOVE_ALL(I8 pt_src, I8 pt_dst, IB move_rsrc, IB move_pins) */
sc_err_t sc_rm_move_all(sc_ipc_t ipc, sc_rm_pt_t pt_src, sc_rm_pt_t pt_dst,
    bool move_rsrc, bool move_pins)
{
    sc_rpc_msg_t msg;
    uint8_t result;

    RPC_VER(&msg) = SC_RPC_VERSION;
    RPC_SVC(&msg) = SC_RPC_SVC_RM;
    RPC_FUNC(&msg) = RM_FUNC_MOVE_ALL;
    RPC_D8(&msg, 0) = pt_src;
    RPC_D8(&msg, 1) = pt_dst;
    RPC_D8(&msg, 2) = move_rsrc;
    RPC_D8(&msg, 3) = move_pins;
    RPC_SIZE(&msg) = 2;

    sc_call_rpc(ipc, &msg, false);

    result = RPC_R8(&msg);
    return result;
}

/* IDL: E8 ASSIGN_RESOURCE(I8 pt, I16 resource) */
sc_err_t sc_rm_assign_resource(sc_ipc_t ipc, sc_rm_pt_t pt,
    sc_rsrc_t resource)
{
    sc_rpc_msg_t msg;
    uint8_t result;

    RPC_VER(&msg) = SC_RPC_VERSION;
    RPC_SVC(&msg) = SC_RPC_SVC_RM;
    RPC_FUNC(&msg) = RM_FUNC_ASSIGN_RESOURCE;
    RPC_D16(&msg, 0) = resource;
    RPC_D8(&msg, 2) = pt;
    RPC_SIZE(&msg) = 2;

    sc_call_rpc(ipc, &msg, false);

    result = RPC_R8(&msg);
    return result;
}

/* IDL: E8 SET_RESOURCE_MOVABLE(I16 resource, IB movable) */
sc_err_t sc_rm_set_resource_movable(sc_ipc_t ipc, sc_rsrc_t resource,
    bool movable)
{
    sc_rpc_msg_t msg;
    uint8_t result;

    RPC_VER(&msg) = SC_RPC_VERSION;
    RPC_SVC(&msg) = SC_RPC_SVC_RM;
    RPC_FUNC(&msg) = RM_FUNC_SET_RESOURCE_MOVABLE;
    RPC_D16(&msg, 0) = resource;
    RPC_D8(&msg, 2) = movable;
    RPC_SIZE(&msg) = 2;

    sc_call_rpc(ipc, &msg, false);

    result = RPC_R8(&msg);
    return result;
}

/* IDL: E8 SET_MASTER_ATTRIBUTES(I16 resource, I4 sa, I4 pa, IB smmu_bypass) */
sc_err_t sc_rm_set_master_attributes(sc_ipc_t ipc, sc_rsrc_t resource,
    sc_rm_spa_t sa, sc_rm_spa_t pa, bool smmu_bypass)
{
    sc_rpc_msg_t msg;
    uint8_t result;

    RPC_VER(&msg) = SC_RPC_VERSION;
    RPC_SVC(&msg) = SC_RPC_SVC_RM;
    RPC_FUNC(&msg) = RM_FUNC_SET_MASTER_ATTRIBUTES;
    RPC_D16(&msg, 0) = resource;
    RPC_D8(&msg, 2) = sa;
    RPC_D8(&msg, 3) = pa;
    RPC_D8(&msg, 4) = smmu_bypass;
    RPC_SIZE(&msg) = 3;

    sc_call_rpc(ipc, &msg, false);

    result = RPC_R8(&msg);
    return result;
}

/* IDL: E8 SET_MASTER_SID(I16 resource, I16 sid) */
sc_err_t sc_rm_set_master_sid(sc_ipc_t ipc, sc_rsrc_t resource,
    sc_rm_sid_t sid)
{
    sc_rpc_msg_t msg;
    uint8_t result;

    RPC_VER(&msg) = SC_RPC_VERSION;
    RPC_SVC(&msg) = SC_RPC_SVC_RM;
    RPC_FUNC(&msg) = RM_FUNC_SET_MASTER_SID;
    RPC_D16(&msg, 0) = resource;
    RPC_D16(&msg, 2) = sid;
    RPC_SIZE(&msg) = 2;

    sc_call_rpc(ipc, &msg, false);

    result = RPC_R8(&msg);
    return result;
}

/* IDL: E8 SET_PERIPHERAL_PERMISSIONS(I16 resource, I8 pt, I4 perm) */
sc_err_t sc_rm_set_peripheral_permissions(sc_ipc_t ipc, sc_rsrc_t resource,
    sc_rm_pt_t pt, sc_rm_perm_t perm)
{
    sc_rpc_msg_t msg;
    uint8_t result;

    RPC_VER(&msg) = SC_RPC_VERSION;
    RPC_SVC(&msg) = SC_RPC_SVC_RM;
    RPC_FUNC(&msg) = RM_FUNC_SET_PERIPHERAL_PERMISSIONS;
    RPC_D16(&msg, 0) = resource;
    RPC_D8(&msg, 2) = pt;
    RPC_D8(&msg, 3) = perm;
    RPC_SIZE(&msg) = 2;

    sc_call_rpc(ipc, &msg, false);

    result = RPC_R8(&msg);
    return result;
}

/* IDL: R1 IS_RESOURCE_OWNED(I16 resource) */
bool sc_rm_is_resource_owned(sc_ipc_t ipc, sc_rsrc_t resource)
{
    sc_rpc_msg_t msg;
    uint8_t result;

    RPC_VER(&msg) = SC_RPC_VERSION;
    RPC_SVC(&msg) = SC_RPC_SVC_RM;
    RPC_FUNC(&msg) = RM_FUNC_IS_RESOURCE_OWNED;
    RPC_D16(&msg, 0) = resource;
    RPC_SIZE(&msg) = 2;

    sc_call_rpc(ipc, &msg, false);

    result = RPC_R8(&msg);
    return result;
}

/* IDL: R1 IS_RESOURCE_MASTER(I16 resource) */
bool sc_rm_is_resource_master(sc_ipc_t ipc, sc_rsrc_t resource)
{
    sc_rpc_msg_t msg;
    uint8_t result;

    RPC_VER(&msg) = SC_RPC_VERSION;
    RPC_SVC(&msg) = SC_RPC_SVC_RM;
    RPC_FUNC(&msg) = RM_FUNC_IS_RESOURCE_MASTER;
    RPC_D16(&msg, 0) = resource;
    RPC_SIZE(&msg) = 2;

    sc_call_rpc(ipc, &msg, false);

    result = RPC_R8(&msg);
    return result;
}

/* IDL: R1 IS_RESOURCE_PERIPHERAL(I16 resource) */
bool sc_rm_is_resource_peripheral(sc_ipc_t ipc, sc_rsrc_t resource)
{
    sc_rpc_msg_t msg;
    uint8_t result;

    RPC_VER(&msg) = SC_RPC_VERSION;
    RPC_SVC(&msg) = SC_RPC_SVC_RM;
    RPC_FUNC(&msg) = RM_FUNC_IS_RESOURCE_PERIPHERAL;
    RPC_D16(&msg, 0) = resource;
    RPC_SIZE(&msg) = 2;

    sc_call_rpc(ipc, &msg, false);

    result = RPC_R8(&msg);
    return result;
}

/* IDL: E8 GET_RESOURCE_INFO(I16 resource, O16 sid) */
sc_err_t sc_rm_get_resource_info(sc_ipc_t ipc, sc_rsrc_t resource,
    sc_rm_sid_t *sid)
{
    sc_rpc_msg_t msg;
    uint8_t result;

    RPC_VER(&msg) = SC_RPC_VERSION;
    RPC_SVC(&msg) = SC_RPC_SVC_RM;
    RPC_FUNC(&msg) = RM_FUNC_GET_RESOURCE_INFO;
    RPC_D16(&msg, 0) = resource;
    RPC_SIZE(&msg) = 2;

    sc_call_rpc(ipc, &msg, false);

    if (sid != NULL)
        *sid = RPC_D16(&msg, 0);
    result = RPC_R8(&msg);
    return result;
}

/* IDL: E8 MEMREG_ALLOC(O8 mr, I64 start, I64 end) */
sc_err_t sc_rm_memreg_alloc(sc_ipc_t ipc, sc_rm_mr_t *mr, sc_faddr_t start,
    sc_faddr_t end)
{
    sc_rpc_msg_t msg;
    uint8_t result;

    RPC_VER(&msg) = SC_RPC_VERSION;
    RPC_SVC(&msg) = SC_RPC_SVC_RM;
    RPC_FUNC(&msg) = RM_FUNC_MEMREG_ALLOC;
    RPC_D32(&msg, 0) = start >> 32;
    RPC_D32(&msg, 4) = start;
    RPC_D32(&msg, 8) = end >> 32;
    RPC_D32(&msg, 12) = end;
    RPC_SIZE(&msg) = 5;

    sc_call_rpc(ipc, &msg, false);

    result = RPC_R8(&msg);
    if (mr != NULL)
        *mr = RPC_D8(&msg, 0);
    return result;
}

/* IDL: E8 MEMREG_FREE(I8 mr) */
sc_err_t sc_rm_memreg_free(sc_ipc_t ipc, sc_rm_mr_t mr)
{
    sc_rpc_msg_t msg;
    uint8_t result;

    RPC_VER(&msg) = SC_RPC_VERSION;
    RPC_SVC(&msg) = SC_RPC_SVC_RM;
    RPC_FUNC(&msg) = RM_FUNC_MEMREG_FREE;
    RPC_D8(&msg, 0) = mr;
    RPC_SIZE(&msg) = 2;

    sc_call_rpc(ipc, &msg, false);

    result = RPC_R8(&msg);
    return result;
}

/* IDL: E8 ASSIGN_MEMREG(I8 pt, I8 mr) */
sc_err_t sc_rm_assign_memreg(sc_ipc_t ipc, sc_rm_pt_t pt, sc_rm_mr_t mr)
{
    sc_rpc_msg_t msg;
    uint8_t result;

    RPC_VER(&msg) = SC_RPC_VERSION;
    RPC_SVC(&msg) = SC_RPC_SVC_RM;
    RPC_FUNC(&msg) = RM_FUNC_ASSIGN_MEMREG;
    RPC_D8(&msg, 0) = pt;
    RPC_D8(&msg, 1) = mr;
    RPC_SIZE(&msg) = 2;

    sc_call_rpc(ipc, &msg, false);

    result = RPC_R8(&msg);
    return result;
}

/* IDL: E8 SET_MEMREG_PERMISSIONS(I8 mr, I8 pt, I4 perm) */
sc_err_t sc_rm_set_memreg_permissions(sc_ipc_t ipc, sc_rm_mr_t mr,
    sc_rm_pt_t pt, sc_rm_perm_t perm)
{
    sc_rpc_msg_t msg;
    uint8_t result;

    RPC_VER(&msg) = SC_RPC_VERSION;
    RPC_SVC(&msg) = SC_RPC_SVC_RM;
    RPC_FUNC(&msg) = RM_FUNC_SET_MEMREG_PERMISSIONS;
    RPC_D8(&msg, 0) = mr;
    RPC_D8(&msg, 1) = pt;
    RPC_D8(&msg, 2) = perm;
    RPC_SIZE(&msg) = 2;

    sc_call_rpc(ipc, &msg, false);

    result = RPC_R8(&msg);
    return result;
}

/* IDL: R1 IS_MEMREG_OWNED(I8 mr) */
bool sc_rm_is_memreg_owned(sc_ipc_t ipc, sc_rm_mr_t mr)
{
    sc_rpc_msg_t msg;
    uint8_t result;

    RPC_VER(&msg) = SC_RPC_VERSION;
    RPC_SVC(&msg) = SC_RPC_SVC_RM;
    RPC_FUNC(&msg) = RM_FUNC_IS_MEMREG_OWNED;
    RPC_D8(&msg, 0) = mr;
    RPC_SIZE(&msg) = 2;

    sc_call_rpc(ipc, &msg, false);

    result = RPC_R8(&msg);
    return result;
}

/* IDL: E8 GET_MEMREG_INFO(I8 mr, O64 start, O64 end) */
sc_err_t sc_rm_get_memreg_info(sc_ipc_t ipc, sc_rm_mr_t mr,
    sc_faddr_t *start, sc_faddr_t *end)
{
    sc_rpc_msg_t msg;
    uint8_t result;

    RPC_VER(&msg) = SC_RPC_VERSION;
    RPC_SVC(&msg) = SC_RPC_SVC_RM;
    RPC_FUNC(&msg) = RM_FUNC_GET_MEMREG_INFO;
    RPC_D8(&msg, 0) = mr;
    RPC_SIZE(&msg) = 2;

    sc_call_rpc(ipc, &msg, false);

    if (start != NULL)
        *start = ((uint64_t) RPC_D32(&msg, 0) << 32) | RPC_D32(&msg, 4);
    if (end != NULL)
        *end = ((uint64_t) RPC_D32(&msg, 8) << 32) | RPC_D32(&msg, 12);
    result = RPC_R8(&msg);
    return result;
}

/* IDL: E8 ASSIGN_PIN(I8 pt, I16 pin) */
sc_err_t sc_rm_assign_pin(sc_ipc_t ipc, sc_rm_pt_t pt, sc_pin_t pin)
{
    sc_rpc_msg_t msg;
    uint8_t result;

    RPC_VER(&msg) = SC_RPC_VERSION;
    RPC_SVC(&msg) = SC_RPC_SVC_RM;
    RPC_FUNC(&msg) = RM_FUNC_ASSIGN_PIN;
    RPC_D16(&msg, 0) = pin;
    RPC_D8(&msg, 2) = pt;
    RPC_SIZE(&msg) = 2;

    sc_call_rpc(ipc, &msg, false);

    result = RPC_R8(&msg);
    return result;
}

/* IDL: R1 IS_PIN_OWNED(I8 pin) */
bool sc_rm_is_pin_owned(sc_ipc_t ipc, sc_pin_t pin)
{
    sc_rpc_msg_t msg;
    uint8_t result;

    RPC_VER(&msg) = SC_RPC_VERSION;
    RPC_SVC(&msg) = SC_RPC_SVC_RM;
    RPC_FUNC(&msg) = RM_FUNC_IS_PIN_OWNED;
    RPC_D8(&msg, 0) = pin;
    RPC_SIZE(&msg) = 2;

    sc_call_rpc(ipc, &msg, false);

    result = RPC_R8(&msg);
    return result;
}

/**@}*/

