/*
 * Copyright (c) 2012-2015, Freescale Semiconductor, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 *
 * o Redistributions of source code must retain the above copyright notice, this list
 *   of conditions and the following disclaimer.
 *
 * o Redistributions in binary form must reproduce the above copyright notice, this
 *   list of conditions and the following disclaimer in the documentation and/or
 *   other materials provided with the distribution.
 *
 * o Neither the name of Freescale Semiconductor, Inc. nor the names of its
 *   contributors may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
 * ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

//----------------------------------------------------------------------------
// zoe_module_data_intf_clnt.h
//
// Description:
//  ZOERPCGEN Generated Header File.
//
// Author: 
//	ZOERPCGEN
//
//----------------------------------------------------------------------------

//
// Generated by zoerpcgen version 1.0.0001 - DO NOT MODIFY!
//


#ifndef __zoe_module_data_intf_clnt_H__
#define __zoe_module_data_intf_clnt_H__


#include "zoe_module_data_intf.h"



// zoe_module_data_intf interface function 0 client function
//
#ifdef __cplusplus
extern "C"
#endif //__cplusplus
zoe_errs_t zoe_module_allocate_buffer_clnt(
    uint32_t sel,
    uint32_t buf_sel,
    uint32_t size,
    zoe_dev_mem_t* dev_mem,
    uint32_t* size_got,
    ZOE_IPC_CPU cpu_id,
    uint32_t module,
    uint32_t inst
    );

// zoe_module_data_intf interface function 1 client function
//
#ifdef __cplusplus
extern "C"
#endif //__cplusplus
zoe_errs_t zoe_module_release_buffer_clnt(
    uint32_t sel,
    uint32_t buf_sel,
    zoe_dev_mem_t dev_mem,
    uint32_t size,
    ZOE_IPC_CPU cpu_id,
    uint32_t module,
    uint32_t inst
    );

// zoe_module_data_intf interface function 2 client function
//
#ifdef __cplusplus
extern "C"
#endif //__cplusplus
zoe_errs_t zoe_module_release_buffer_with_info_clnt(
    uint32_t sel,
    uint32_t buf_sel,
    zoe_dev_mem_t dev_mem,
    uint32_t size,
    ZOE_BUFFER_INFO* buf_info,
    ZOE_IPC_CPU cpu_id,
    uint32_t module,
    uint32_t inst
    );

// zoe_module_data_intf interface function 3 client function
//
#ifdef __cplusplus
extern "C"
#endif //__cplusplus
zoe_errs_t zoe_module_allocate_yuv_buffer_clnt(
    uint32_t sel,
    uint32_t num_planes,
    uint32_t size[3],
    zoe_dev_mem_t dev_mem[3],
    ZOE_IPC_CPU cpu_id,
    uint32_t module,
    uint32_t inst
    );

// zoe_module_data_intf interface function 4 client function
//
#ifdef __cplusplus
extern "C"
#endif //__cplusplus
zoe_errs_t zoe_module_release_yuv_buffer_clnt(
    uint32_t sel,
    uint32_t num_planes,
    zoe_dev_mem_t dev_mem[3],
    uint32_t size[3],
    ZOE_IPC_CPU cpu_id,
    uint32_t module,
    uint32_t inst
    );

// zoe_module_data_intf interface function 5 client function
//
#ifdef __cplusplus
extern "C"
#endif //__cplusplus
zoe_errs_t zoe_module_release_yuv_buffer_with_info_clnt(
    uint32_t sel,
    uint32_t num_planes,
    zoe_dev_mem_t dev_mem[3],
    uint32_t size[3],
    ZOE_BUFFER_INFO* buf_info,
    ZOE_IPC_CPU cpu_id,
    uint32_t module,
    uint32_t inst
    );

// zoe_module_data_intf interface function 6 client function
//
#ifdef __cplusplus
extern "C"
#endif //__cplusplus
zoe_errs_t zoe_module_get_mem_type_clnt(
    uint32_t sel,
    uint32_t* mem_type,
    ZOE_IPC_CPU cpu_id,
    uint32_t module,
    uint32_t inst
    );

// zoe_module_data_intf interface function 7 client function
//
#ifdef __cplusplus
extern "C"
#endif //__cplusplus
zoe_errs_t zoe_module_get_mem_usage_clnt(
    uint32_t sel,
    uint32_t* mem_usage,
    ZOE_IPC_CPU cpu_id,
    uint32_t module,
    uint32_t inst
    );

// zoe_module_data_intf interface function 8 client function
//
#ifdef __cplusplus
extern "C"
#endif //__cplusplus
zoe_errs_t zoe_module_write_clnt(
    uint32_t sel,
    ZOE_BUFFER_DESCRIPTOR* buf_desc,
    ZOE_IPC_CPU cpu_id,
    uint32_t module,
    uint32_t inst
    );

// zoe_module_data_intf interface function 9 client function
//
#ifdef __cplusplus
extern "C"
#endif //__cplusplus
zoe_errs_t zoe_module_buffer_available_clnt(
    uint32_t sel,
    uint32_t buf_sel,
    ZOE_IPC_CPU cpu_id,
    uint32_t module,
    uint32_t inst
    );

#endif //__zoe_module_data_intf_clnt_H__
