/*
 * Copyright (c) 2012-2015, Freescale Semiconductor, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 *
 * o Redistributions of source code must retain the above copyright notice, this list
 *   of conditions and the following disclaimer.
 *
 * o Redistributions in binary form must reproduce the above copyright notice, this
 *   list of conditions and the following disclaimer in the documentation and/or
 *   other materials provided with the distribution.
 *
 * o Neither the name of Freescale Semiconductor, Inc. nor the names of its
 *   contributors may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
 * ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

//----------------------------------------------------------------------------
// zoe_module_vdec_intf.h
//
// Description:
//  ZOERPCGEN Generated Header File.
//
// Author: 
//	ZOERPCGEN
//
//----------------------------------------------------------------------------

//
// Generated by zoerpcgen version 1.0.0001 - DO NOT MODIFY!
//


#ifndef __zoe_module_vdec_intf_H__
#define __zoe_module_vdec_intf_H__


// API version
//
#define zoe_module_vdec_intf_version     0x3

// API interface number
//
#define zoe_module_vdec_intf_interface   0x7


typedef struct _VPU_PLANE
{
    uint32_t            sizeimage;
    uint32_t            stride;
    uint32_t            data_offset;
} VPU_PLANE;


typedef struct _VPU_PICTURE
{
    uint32_t            width_dec;
    uint32_t            height_dec;
    uint32_t            width_disp;
    uint32_t            height_disp;
    uint32_t            pixelformat;
    uint32_t            colorspace;
    uint32_t            alignment;
    uint32_t            is10bits;
    uint32_t            colocated_width;
    uint32_t            colocated_height;
    uint32_t            colocated_size;
    uint32_t            num_planes;
    VPU_PLANE           planes[2];
} VPU_PICTURE;


typedef struct _VPU_CROP_WINDOW
{
    uint32_t            top;
    uint32_t            bottom;
    uint32_t            left;
    uint32_t            right;
} VPU_CROP_WINDOW;



#endif //__zoe_module_vdec_intf_H__
