/*
 * Copyright (c) 2012-2015, Freescale Semiconductor, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 *
 * o Redistributions of source code must retain the above copyright notice, this list
 *   of conditions and the following disclaimer.
 *
 * o Redistributions in binary form must reproduce the above copyright notice, this
 *   list of conditions and the following disclaimer in the documentation and/or
 *   other materials provided with the distribution.
 *
 * o Neither the name of Freescale Semiconductor, Inc. nor the names of its
 *   contributors may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
 * ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

//----------------------------------------------------------------------------
// zoe_module_vdec_intf_srv.h
//
// Description:
//  ZOERPCGEN Generated Header File.
//
// Author: 
//	ZOERPCGEN
//
//----------------------------------------------------------------------------

//
// Generated by zoerpcgen version 1.0.0001 - DO NOT MODIFY!
//


#ifndef __zoe_module_vdec_intf_srv_H__
#define __zoe_module_vdec_intf_srv_H__


#include "zoe_module_vdec_intf.h"


// zoe_module_vdec_intf interface dispatch function
//
#ifdef __cplusplus
extern "C"
#endif //__cplusplus
zoe_errs_t zoe_module_vdec_intf_dispatch(
    void *pContext,
    ZOE_IPC_CPU from_cpu,
    PZOE_IPC_MSG pMsg
    );


// zoe_module_vdec_intf interface function 0 server implementation
//
#ifdef __cplusplus
extern "C"
#endif //__cplusplus
zoe_errs_t zoe_module_vdec_format_set_srv(
    uint32_t fmt,
    void * pContext
    );

// zoe_module_vdec_intf interface function 1 server implementation
//
#ifdef __cplusplus
extern "C"
#endif //__cplusplus
zoe_errs_t zoe_module_vdec_format_get_srv(
    uint32_t* fmt,
    void * pContext
    );

// zoe_module_vdec_intf interface function 2 server implementation
//
#ifdef __cplusplus
extern "C"
#endif //__cplusplus
zoe_errs_t zoe_module_vdec_mode_set_srv(
    uint32_t mode,
    void * pContext
    );

// zoe_module_vdec_intf interface function 3 server implementation
//
#ifdef __cplusplus
extern "C"
#endif //__cplusplus
zoe_errs_t zoe_module_vdec_mode_get_srv(
    uint32_t* mode,
    void * pContext
    );

// zoe_module_vdec_intf interface function 4 server implementation
//
#ifdef __cplusplus
extern "C"
#endif //__cplusplus
zoe_errs_t zoe_module_vdec_order_set_srv(
    uint32_t order,
    void * pContext
    );

// zoe_module_vdec_intf interface function 5 server implementation
//
#ifdef __cplusplus
extern "C"
#endif //__cplusplus
zoe_errs_t zoe_module_vdec_order_get_srv(
    uint32_t* order,
    void * pContext
    );

// zoe_module_vdec_intf interface function 6 server implementation
//
#ifdef __cplusplus
extern "C"
#endif //__cplusplus
zoe_errs_t zoe_module_vdec_yuv_format_set_srv(
    uint32_t pixelformat,
    void * pContext
    );

// zoe_module_vdec_intf interface function 7 server implementation
//
#ifdef __cplusplus
extern "C"
#endif //__cplusplus
zoe_errs_t zoe_module_vdec_yuv_format_get_srv(
    VPU_PICTURE* fmt,
    void * pContext
    );

// zoe_module_vdec_intf interface function 8 server implementation
//
#ifdef __cplusplus
extern "C"
#endif //__cplusplus
zoe_errs_t zoe_module_vdec_get_required_nb_fb_srv(
    uint32_t* nb,
    void * pContext
    );

// zoe_module_vdec_intf interface function 9 server implementation
//
#ifdef __cplusplus
extern "C"
#endif //__cplusplus
zoe_errs_t zoe_module_vdec_get_required_vbv_size_srv(
    uint32_t* size,
    void * pContext
    );

// zoe_module_vdec_intf interface function 10 server implementation
//
#ifdef __cplusplus
extern "C"
#endif //__cplusplus
zoe_errs_t zoe_module_vdec_get_crop_srv(
    VPU_CROP_WINDOW* crop,
    void * pContext
    );

#endif //__zoe_module_vdec_intf_srv_H__
