/*
 * Copyright (c) 2012-2015, Freescale Semiconductor, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 *
 * o Redistributions of source code must retain the above copyright notice, this list
 *   of conditions and the following disclaimer.
 *
 * o Redistributions in binary form must reproduce the above copyright notice, this
 *   list of conditions and the following disclaimer in the documentation and/or
 *   other materials provided with the distribution.
 *
 * o Neither the name of Freescale Semiconductor, Inc. nor the names of its
 *   contributors may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
 * ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

//----------------------------------------------------------------------------
// zoe_module_connection_intf.h
//
// Description:
//  ZOERPCGEN Generated Header File.
//
// Author: 
//	ZOERPCGEN
//
//----------------------------------------------------------------------------

//
// Generated by zoerpcgen version 1.0.0001 - DO NOT MODIFY!
//


#ifndef __zoe_module_connection_intf_H__
#define __zoe_module_connection_intf_H__


// API version
//
#define zoe_module_connection_intf_version     0x1

// API interface number
//
#define zoe_module_connection_intf_interface   0x1


typedef struct _ZOE_MODULE_ADDR
{
    uint32_t            cpu;
    uint32_t            module;
    uint32_t            inst;
} ZOE_MODULE_ADDR;


typedef struct _ZOE_MODULE_DATA_CONNECTOR
{
    ZOE_MODULE_ADDR     addr;
    uint32_t            selector;
} ZOE_MODULE_DATA_CONNECTOR;



#endif //__zoe_module_connection_intf_H__
