/*==========================================================================*/
/*!
 * @file svc/pm/rpc.h
 *
 * Header file for the PM RPC implementation.
 *
 * @addtogroup PM_SVC
 * @{
 */
/*==========================================================================*/

/* DO NOT EDIT - This file auto generated by rpc_h.pl */

#ifndef _SC_PM_RPC_H
#define _SC_PM_RPC_H

/* Includes */

#include <soc/imx8/sc/rpc.h>

/* Defines */

/* Types */

typedef enum pm_func_e
{
    PM_FUNC_UNKNOWN,
    PM_FUNC_SET_SYS_POWER_MODE,
    PM_FUNC_GET_SYS_POWER_MODE,
    PM_FUNC_SET_RESOURCE_POWER_MODE,
    PM_FUNC_GET_RESOURCE_POWER_MODE,
    PM_FUNC_SET_CLOCK_RATE,
    PM_FUNC_GET_CLOCK_RATE,
    PM_FUNC_CLOCK_ENABLE,
    PM_FUNC_BOOT,
    PM_FUNC_REBOOT,
    PM_FUNC_RESET_REASON,
    PM_FUNC_CPU_START
} pm_func_t;

/* Functions */

void pm_dispatch(sc_rm_pt_t caller_pt, sc_rpc_msg_t *msg);

#endif /* _SC_PM_RPC_H */

/**@}*/

