/*==========================================================================*/
/*!
 * @file svc/timer/rpc_clnt.c
 *
 * File containing client-side RPC functions for the TIMER service. These
 * function are ported to clients that communicate to the SC.
 *
 * @addtogroup TIMER_SVC
 * @{
 */
/*==========================================================================*/

/* DO NOT EDIT - This file auto generated by rpc_clnt_c.pl */

/* Includes */

#include <soc/imx8/sc/types.h>
#include <soc/imx8/sc/svc/rm/api.h>
#include <soc/imx8/sc/svc/timer/api.h>
#include "../../main/rpc.h"
#include "rpc.h"

/* Local Defines */

/* Local Types */

/* IDL: E8 SET_WDOG_TIMEOUT(I32 timeout) */
sc_err_t sc_timer_set_wdog_timeout(sc_ipc_t ipc,
    sc_timer_wdog_time_t timeout)
{
    sc_rpc_msg_t msg;
    uint8_t result;

    RPC_VER(&msg) = SC_RPC_VERSION;
    RPC_SVC(&msg) = SC_RPC_SVC_TIMER;
    RPC_FUNC(&msg) = TIMER_FUNC_SET_WDOG_TIMEOUT;
    RPC_D32(&msg, 0) = timeout;
    RPC_SIZE(&msg) = 2;

    sc_call_rpc(ipc, &msg, false);

    result = RPC_R8(&msg);
    return result;
}

/* IDL: E8 START_WDOG(IB lock) */
sc_err_t sc_timer_start_wdog(sc_ipc_t ipc, bool lock)
{
    sc_rpc_msg_t msg;
    uint8_t result;

    RPC_VER(&msg) = SC_RPC_VERSION;
    RPC_SVC(&msg) = SC_RPC_SVC_TIMER;
    RPC_FUNC(&msg) = TIMER_FUNC_START_WDOG;
    RPC_D8(&msg, 0) = lock;
    RPC_SIZE(&msg) = 2;

    sc_call_rpc(ipc, &msg, false);

    result = RPC_R8(&msg);
    return result;
}

/* IDL: E8 STOP_WDOG() */
sc_err_t sc_timer_stop_wdog(sc_ipc_t ipc)
{
    sc_rpc_msg_t msg;
    uint8_t result;

    RPC_VER(&msg) = SC_RPC_VERSION;
    RPC_SVC(&msg) = SC_RPC_SVC_TIMER;
    RPC_FUNC(&msg) = TIMER_FUNC_STOP_WDOG;
    RPC_SIZE(&msg) = 1;

    sc_call_rpc(ipc, &msg, false);

    result = RPC_R8(&msg);
    return result;
}

/* IDL: E8 PING_WDOG() */
sc_err_t sc_timer_ping_wdog(sc_ipc_t ipc)
{
    sc_rpc_msg_t msg;
    uint8_t result;

    RPC_VER(&msg) = SC_RPC_VERSION;
    RPC_SVC(&msg) = SC_RPC_SVC_TIMER;
    RPC_FUNC(&msg) = TIMER_FUNC_PING_WDOG;
    RPC_SIZE(&msg) = 1;

    sc_call_rpc(ipc, &msg, false);

    result = RPC_R8(&msg);
    return result;
}

/* IDL: E8 GET_WDOG_STATUS(O32 timeout, O32 max_timeout, O32 remaining_time) */
sc_err_t sc_timer_get_wdog_status(sc_ipc_t ipc,
    sc_timer_wdog_time_t *timeout, sc_timer_wdog_time_t *max_timeout,
    sc_timer_wdog_time_t *remaining_time)
{
    sc_rpc_msg_t msg;
    uint8_t result;

    RPC_VER(&msg) = SC_RPC_VERSION;
    RPC_SVC(&msg) = SC_RPC_SVC_TIMER;
    RPC_FUNC(&msg) = TIMER_FUNC_GET_WDOG_STATUS;
    RPC_SIZE(&msg) = 1;

    sc_call_rpc(ipc, &msg, false);

    if (timeout != NULL)
        *timeout = RPC_D32(&msg, 0);
    if (max_timeout != NULL)
        *max_timeout = RPC_D32(&msg, 4);
    if (remaining_time != NULL)
        *remaining_time = RPC_D32(&msg, 8);
    result = RPC_R8(&msg);
    return result;
}

/* IDL: E8 SET_RTC_TIME(I16 year, I8 mon, I8 day, I8 hour, I8 min, I8 sec) */
sc_err_t sc_timer_set_rtc_time(sc_ipc_t ipc, uint16_t year, uint8_t mon,
    uint8_t day, uint8_t hour, uint8_t min, uint8_t sec)
{
    sc_rpc_msg_t msg;
    uint8_t result;

    RPC_VER(&msg) = SC_RPC_VERSION;
    RPC_SVC(&msg) = SC_RPC_SVC_TIMER;
    RPC_FUNC(&msg) = TIMER_FUNC_SET_RTC_TIME;
    RPC_D16(&msg, 0) = year;
    RPC_D8(&msg, 2) = mon;
    RPC_D8(&msg, 3) = day;
    RPC_D8(&msg, 4) = hour;
    RPC_D8(&msg, 5) = min;
    RPC_D8(&msg, 6) = sec;
    RPC_SIZE(&msg) = 3;

    sc_call_rpc(ipc, &msg, false);

    result = RPC_R8(&msg);
    return result;
}

/* IDL: E8 GET_RTC_TIME(O16 year, O8 mon, O8 day, O8 hour, O8 min, O8 sec) */
sc_err_t sc_timer_get_rtc_time(sc_ipc_t ipc, uint16_t *year, uint8_t *mon,
    uint8_t *day, uint8_t *hour, uint8_t *min, uint8_t *sec)
{
    sc_rpc_msg_t msg;
    uint8_t result;

    RPC_VER(&msg) = SC_RPC_VERSION;
    RPC_SVC(&msg) = SC_RPC_SVC_TIMER;
    RPC_FUNC(&msg) = TIMER_FUNC_GET_RTC_TIME;
    RPC_SIZE(&msg) = 1;

    sc_call_rpc(ipc, &msg, false);

    if (year != NULL)
        *year = RPC_D16(&msg, 0);
    result = RPC_R8(&msg);
    if (mon != NULL)
        *mon = RPC_D8(&msg, 2);
    if (day != NULL)
        *day = RPC_D8(&msg, 3);
    if (hour != NULL)
        *hour = RPC_D8(&msg, 4);
    if (min != NULL)
        *min = RPC_D8(&msg, 5);
    if (sec != NULL)
        *sec = RPC_D8(&msg, 6);
    return result;
}

/* IDL: E8 SET_RTC_ALARM(I16 year, I8 mon, I8 day, I8 hour, I8 min, I8 sec) */
sc_err_t sc_timer_set_rtc_alarm(sc_ipc_t ipc, uint16_t year, uint8_t mon,
    uint8_t day, uint8_t hour, uint8_t min, uint8_t sec)
{
    sc_rpc_msg_t msg;
    uint8_t result;

    RPC_VER(&msg) = SC_RPC_VERSION;
    RPC_SVC(&msg) = SC_RPC_SVC_TIMER;
    RPC_FUNC(&msg) = TIMER_FUNC_SET_RTC_ALARM;
    RPC_D16(&msg, 0) = year;
    RPC_D8(&msg, 2) = mon;
    RPC_D8(&msg, 3) = day;
    RPC_D8(&msg, 4) = hour;
    RPC_D8(&msg, 5) = min;
    RPC_D8(&msg, 6) = sec;
    RPC_SIZE(&msg) = 3;

    sc_call_rpc(ipc, &msg, false);

    result = RPC_R8(&msg);
    return result;
}

/**@}*/

