/*==========================================================================*/
/*!
 * @file svc/misc/rpc.h
 *
 * Header file for the MISC RPC implementation.
 *
 * @addtogroup MISC_SVC
 * @{
 */
/*==========================================================================*/

/* DO NOT EDIT - This file auto generated by rpc_h.pl */

#ifndef _SC_MISC_RPC_H
#define _SC_MISC_RPC_H

/* Includes */

/* Defines */

/* Types */

/*!
 * This type is used to indicate RPC MISC function calls.
 */
typedef enum misc_func_e
{
    MISC_FUNC_UNKNOWN, //!< Unknown function
    MISC_FUNC_SET_CONTROL, //!< Index for misc_set_control() RPC call
    MISC_FUNC_GET_CONTROL, //!< Index for misc_get_control() RPC call
} misc_func_t;

/* Functions */

/*!
 * @name Internal RPC Function
 * @{
 */

/*!
 * This function dispatches an incoming MISC RPC request.
 *
 * @param[in]     caller_pt   caller partition
 * @param[in]     msg         pointer to RPC message
 */
void misc_dispatch(sc_rm_pt_t caller_pt, sc_rpc_msg_t *msg);

/* @} */

#endif /* _SC_MISC_RPC_H */

/**@}*/

